---
- name: Add Mosquitto repositories
  apt_repository: >
    repo='{{ item }}'
    state=present
  with_items:
    - 'ppa:mosquitto-dev/mosquitto-ppa'

- name: Add Mosquitto key
  apt_key: >
    url='http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key'
    state=present

- name: Install Mosquitto Broker, Clients, and API
  apt: >
    update_cache=yes
    pkg={{ item }}
    state=installed
  with_items:
    - mosquitto
    - mosquitto-clients
    - python-mosquitto



