# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder "../../../../mosquitto-ansible-role", "/home/vagrant/mosquitto-ansible-role"
  config.vm.provision "shell", privileged: false, path: "run-ansible.sh"
end
